name: Demo composite actions

on:
  workflow_dispatch:

jobs:
  Demo_calling_composite_actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Call composite action
        id: step1
        uses: ./.github/actions/demo_composite-action
        with:
          greeting: "Good morning"
          name: "Thanh"

      - name: Print output from last step
        run: echo "${{steps.step1.outputs.full-greeting}}"
